version: 2
jobs:
  build:
    docker:
      - image: hostedgraphite/pythonbuild:focal_build3
    environment:
      CIRCLE_ARTIFACTS: /tmp/artifacts
    steps:
      - checkout
      - run: mkdir -p $CIRCLE_ARTIFACTS
      - run: make lint
      - run: make test
      - run: cp -r cover $CIRCLE_ARTIFACTS
      - store_artifacts:
          path: /tmp/artifacts
